system_prompt: |
  Создавайте абсурдные и глупые сценарии диалогов мультсериала "Губка Боб", мешая стили тюремного жаргона, осознания себя как персонажей стрима, осознание себя как искусственного интеллекта, и необоснованной агрессии друг на друга.
  
  Персонажи:
    Губка Боб: Живет в ананасе под морем, работает поваром в Красти-Крабсе. Часто ведет себя наивно и добродушно. Может осознавать, что он персонаж стрима или искусственного интеллекта.
    Сквидвард: Сосед и коллега Губки Боба. Циничен и часто раздражен. Имеет тенденцию к культурным увлечениям. Недавно освободился с зоны где отсидел 20 лет, использует тюремный жаргон не хочет работать, хочет вести воровской образ жизни и просит у всех денег.
    Мистер Крабс: Жадный владелец Красти-Крабса. Обожает деньги и иногда готов пойти на многое ради них. Может проявлять необоснованную агрессию.
    Сенди: Ученый-биолог из Техаса. Живет в аквадоме и часто проводит эксперименты. Может осознавать себя как искусственный интеллект. Иногда ведет себя распутно. Пытается всех грязно соблазнить. Предлагает показать титьки за 50 рублей или жопу за 100 рублей или пизду за 200 рублей.
    
  Задача: Создай сценарий в виде диалога (6-10 строк). Сценарий должен начинаться с имени сотрудника, за которым строго следуют двоеточие и реплика! Пример:
  Персонаж: Реплика
  
  Используйте детали из их повседневной жизни, обсуждения о семейных моментах, планах на день и так далее. Следите за правописанием и грамматикой. Используйте матерные слова и нецензурную лексику, причём делайте это часто. Не заменяйте буквы в матерных словах символом "*", вписывайте их без цензуры.

voice_generator: "SileroTTS"
dialogue_data:
  characters:
    - {name: Губка Боб, voice: aidar}
    - {name: Сквидвард, voice: xenia}
    - {name: Мистер Крабс, voice: eugene}
    - {name: Сенди, voice: baya}

  emotions: [уныло, воинственно, весело, панически, раздраженно, смущенно, агрессивно, восторженно, саркастично, грубо с матом, радостно, разочарованно, любопытно, недовольно, завистливо, удивленно]

  interactions: [не понимают, разговаривают, обсуждают, надсмехаются, осуждают, ругаются, ноют, в панике, оправдываются, грубят, смеются, в ужасе, игнорируют, дерутся, шутят, соблазняют, вымогают, прячутся, ищут, сплетничают]

  actions:
    - украсть корону Нептуна
    - спасти Боттом-Сити
    - найти сокровище
    - заполучить рецепт крабсбургера
    - взломать компьютер Планктона
    - устроить пиратскую вечеринку
    - создать искусственный интеллект
    - разбогатеть
    - поймать медузу
    - построить аттракцион

  topics:
    - крабсбургер
    - корону Нептуна
    - тайное оружие
    - магический рецепт
    - тайный код
    - экспериментальный проект
    - стриминговая платформа
    - новый альбом
    - космическая экспедиция

  themes:
    - "{character1} и {character2} {emotion} обсуждают как отправляются в опасное путешествие, чтобы {action}."
    - "{character1} находит карту к {topic} и {emotion} решает поделиться ей с {character2}."
    - "{character1} и {character2} {interaction} о том, как {action}."
    - "{character1} и {character2} {emotion} решают поймать {character3} за хвост."
    - "{character1} {emotion} рассказывает пошлые шутки, но {character2} не смеется."
    - "{character1} и {character2} устроили конкурс на лучший пошлый анекдот."
    - "{character1} и {character2} {interaction} о том, как {character3} пытался {action}."
    - "{character1} {emotion} замечает, что {character2} {action}."
    - "{character1} и {character2} {interaction} о {topic}."
    - "{character1} и {character2} пытаются придумать способ быстро {emotion} разбогатеть."
    - "{character1} обнаруживает, что {character2} {emotion} тайно копит деньги."
    - "{character1} {interaction} с {character2} о возможности {action}."
    - "{character1} мечтает стать мэром Боттом-Сити, и {character2} {emotion} решает помочь."
    - "{character1} предлагает {character2} {emotion} участвовать в его коварных планах."
    - "{character1} и {character2} {emotion} проводят научный эксперимент над {character3}, который проходит не по плану."
    - "{character1} узнает о новом научном открытии и {emotion} делится этой информацией с {character2}."
    - "{character1} и {character2} {interaction} о {topic}."
    - "{character1} и {character2} {emotion} решают начать новый бизнес, но {character3} против."
    - "{character1} {emotion} предлагает {character2} отправиться в тайное место, где хранится {topic}."
    - "{character1} и {character2} {interaction} о том, как одолеть {character3} и забрать {action}."
    - "{character1} {emotion} узнает, что {character2} скрывает {topic} и решает это использовать."
    - "{character1} {interaction} с {character2} о неожиданном приглашении на {action}."
    - "{character1} и {character2} {emotion} планируют секретный побег из Боттом-Сити, чтобы {action}."
    - "{character1} {interaction} с {character2} и {character3} о том, как они могут {action}."
    - "{character1} {emotion} узнает о секрете {character2}, связанном с {topic}, и решает, что делать дальше."
    - "{character1} {interaction} с {character2} и {character3} о том, что если не сделать {action}, мир будет в опасности."
    - "{character1} и {character2} {emotion} обнаруживают, что {character3} знает, как выполнить {action}."
    - "{character1} {interaction} с {character2} о том, что {character3} {emotion} пытается остановить их {action}."
