version: '3'
services:
  app:
    image: python:3.10-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python main.py"
    environment:
      - PYTHONUNBUFFERED=1
